apiVersion: v1
kind: Service
metadata:
  name: todo-app-external
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000  # 30000-32767 범위 (생략 시 자동할당)
