apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
      version: v1
  template:
    metadata:
      labels:
        app: todo
        version: v1
    spec:
      containers:
      - name: todo-app
        image: todo-app:v1
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
      version: v2
  template:
    metadata:
      labels:
        app: todo
        version: v2
    spec:
      containers:
      - name: todo-app
        image: todo-app:v2
        ports:
        - containerPort: 8000
